name: satcon
on: 
  push:
    branches:
      - main
  workflow_dispatch:
    
  
jobs:
  # This workflow contains just one single job: "build"
  build:
    # It will run on local self-hosted runner yoga
    runs-on: [self-hosted, yoga]
    # Execute this set of instructions:
    steps:
      - name: Checkout code
        # Download the repo to the current workspace
        uses: actions/checkout@v2
      - name: Deploy to Tomcat
        run: curl --upload-file "C:\Data\workspace\satcon\satcon.war" "http://admin:admin01>@localhost:80/manager/text/deploy?path=/satex&update=true"
