name: satcon
on: 
  push:
    branches:
      - main
    paths:
      - 'C:\data\workspace\satcon\satcon.war'
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Deploy to Tomcat
      run: |
        curl --upload-file "C:\Data\workspace\satcon\satcon.war" "http://admin:admin01>@localhost:80/manager/text/deploy?path=/satex&update=true"
